language: c
dist: bionic

compiler:
  - clang
  - gcc

git:
  depth: 1
  quiet: true

env:
  - PROJ_INSTALL_DIR=$HOME/install

before_install:
  - sudo apt-get update
  - sudo apt-get install -y libcurl4-openssl-dev

before_script:
  - mkdir -p $PROJ_INSTALL_DIR
  - ROOT_OF_REPO=$(pwd)

script:
  # Build project
  - mkdir build && cd build
  - cmake .. -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=$PROJ_INSTALL_DIR
  - make
  - make install
  # Build/Package minimalist example
  - cd $ROOT_OF_REPO/examples/minimalist
  - mkdir build && cd build
  - cmake .. -DCMAKE_BUILD_TYPE=Debug -DCMAKE_PREFIX_PATH=$PROJ_INSTALL_DIR
  - make
  - make aws-lambda-package-minimalist